### ISSUE TITLE
When all attributes are unchecked, map throws lots of errors

### ISSUE THREAD

**Issue by CartoAZ** [geog575-spring2016/best-places-to-live#58]
When all attributes are unchecked, score = NaN. I added a conditional in the updatePropSymbols function where it returns radius(d.properties.Score) so that NaN sets the radius to 1.

Since we're scaling the circles, this makes all of them look pretty big, which isn't good. Is it possible to bypass the radius generator with our domain and range and just set all circles to a radius of 1 or 2 so we can see their locations but it doesn't look like they have a score?

**Comment by dmschumacher** [comment]
We can definitely work on figuring our a scaling system that works but I think it'd be easiest to do in person. I think it would be pretty easy to skip the radius generator thing as long as we are able to detect when none of the boxes are checked. ie if(number of checked boxes > 1){ scale using radius generator} else{set radius to 1}

**Comment by CartoAZ** [comment]
Added a line to set radius of circles to 5 when no score is generated.
